### PR TITLE
Added fibonacci distribution

### PR DESCRIPTION
**Pull request by harisreedhar**

### CODE REVIEW

**Comment by 3DSinghVFX** [comment]
Thanks.
Can you please add an example of this? I'll review the code soon.

**Comment by harisreedhar** [comment]
fibdemo

**Comment by 3DSinghVFX** [comment]
Thanks :) You can create the pull request directly to [AnimationNodes/master](https://github.com/JacquesLucke/animation_nodes/pulls) with this example, we will review the code there.

**Comment by 3DSinghVFX** [comment]
Thanks.

**Pull request closed without merging**
